export const SUCCESS = 'Email sent successfully';
export const FAIL = 'Fail to send the email';
export const SERVICE_BROKEN = 'Mail Cop Internal Error';
export const INVALID_FROM = 'FROM field is not valid, email required';
export const INVALID_TO = 'TO field is not valid, email array required';
export const INVALID_CC = 'CC field is not valid, email array required';
export const INVALID_BCC = 'BCC field is not valid, email array required';
export const INVALID_SUBJECT = 'SUBJECT field is not valid, non-empty string required';
export const INVALID_TEXT = 'TEXT field is not valid, non-empty string required';